In [ ]:
import numpy as np

# Vectors


## row vector
$$
\begin{bmatrix}
1 & 2 & 3
\end{bmatrix}
$$
## column vector
$$
\begin{bmatrix}
1 \\
2\\
3
\end{bmatrix}
$$


In [ ]:
row_vector = np.array([1, 2, 3])
print(row_vector)
print()

col_vector = np.array([[1], [2], [3]])
print(col_vector)
print()

[1 2 3]

[[1]
 [2]
 [3]]



## Vector operation with scalar value

In [ ]:
u = np.array([3,2,6])
print(u+2)
print(u-2)
print(u*2)
print(u/2)

[5 4 8]
[1 0 4]
[ 6  4 12]
[1.5 1.  3. ]


## Vector Operations
$$ u = \begin{bmatrix} 1 & 3 & 5\end{bmatrix}$$
$$ u = \begin{bmatrix} 2 & 6 & 4 \end{bmatrix}$$

In [ ]:
u = np.array([1, 3, 5])
v = np.array([2, 6, 4])
print(u + v)
print(u - v)

[3 9 9]
[-1 -3  1]


## dot product
$$
u = \begin{bmatrix} a & b & c\end{bmatrix}\\
v = \begin{bmatrix} x & y & z\end{bmatrix}\\
u \cdot v = ax+by+cz \\
\begin{align*}
&= 1\times2 + 3\times6 + 5\times4 \\
&= 2+ 18+ 20 \\
&= 40
\end{align*}
$$


In [ ]:
# dot product
print(np.dot(u, v))

40


## cross product
$$
u \times v = \begin{vmatrix}
i & j & k \\
a & b & c \\
x & y & z
 \end{vmatrix} = (bz-cy)i - (az-cx)j + (ay-bx)k
$$

$$
u \times v
= \begin{vmatrix}
i & j & k \\
1 & 3 & 5 \\
2 & 6 & 4
 \end{vmatrix} \\
 \begin{align*}
 &= (3\times 4 - 5\times6)i - (1\times4-5\times2)j + (1\times6-3\times2)k \\
 &=(12-30)i-(4-10)j+(6-6)k \\
 &= -18i +6j+ 0k \\
&= \begin{bmatrix}-18&6&0\end{bmatrix}
\end{align*}
$$

In [ ]:
print(np.cross(u, v))

[-18   6   0]


In [ ]:
print(np.cross(v,u))

[18 -6  0]


# Matrix
$$
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
$$

In [ ]:
M = np.array([[1,2],[3,4]])
print(M)

[[1 2]
 [3 4]]


In [ ]:
z = np.zeros((2, 3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
one = np.ones((2, 3))
print(one)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
i = np.eye(3) #identity matrix
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Transpose
matrix = np.array([[1, 2], [3, 4]])
print(matrix)
print()

print(matrix.transpose())

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [ ]:
matrix[0][0]

1

$$\begin{pmatrix}
a_{0,0} & \cdots & a_{0,m}\\
\vdots & \ddots & \vdots \\
a_{n,0} & \cdots & a_{n,m}
\end{pmatrix}
$$

# Matrix operations

In [ ]:
M = np.array([[1, 2], [3, 4]])
N = np.array([[7, 8],[6, 5]])
print(M + N)
print()
print(M - N)

[[ 8 10]
 [ 9  9]]

[[-6 -6]
 [-3 -1]]


In [ ]:
M = np.array([[1, 2], [3, 4]])
P = np.array([[7, 8, 9],[6, 5, 4]])
M + P

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

for matrix multiplications,
$A_{a\times m} \times B_{m \times b} = C_{a \times b}$

In [ ]:
A = np.matrix([[1,2],[3,4]])
B = np.matrix([[2,4,6],[6,8,0]])
print(A * B)

[[14 20  6]
 [30 44 18]]


In [ ]:
print(np.dot(A,B))

[[14 20  6]
 [30 44 18]]


$$
A = \begin{bmatrix}1 & 2\\ 3 & 4\end{bmatrix} , B = \begin{bmatrix}2 & 4 & 6\\ 6 & 8 & 0\end{bmatrix} \\
\begin{align*}
A \cdot B &= \begin{bmatrix}1 & 2\\ 3 & 4\end{bmatrix} \cdot \begin{bmatrix}2 & 4 & 6\\ 6 & 8 & 0\end{bmatrix} \\
&= \begin{bmatrix}
1 \times 2+2\times 6 & 1 \times 4+2\times 8 & 1 \times 6+2\times 0\\
3 \times 2+4\times 6 & 3 \times 4+4\times 8 & 3 \times 6+4\times 0
\end{bmatrix}\\
&= \begin{bmatrix}
2+12 & 4+16 & 6+0\\
6+24 & 12+32 & 18+0
\end{bmatrix}\\
&= \begin{bmatrix}
14 & 20 & 6\\
30 & 44 & 18
\end{bmatrix}\\
\end{align*}
$$

# Determinant
$$
A = \begin{bmatrix}
a & b & c\\
d & e & f\\
g & h & i
\end{bmatrix} \\
|A| = a \times \begin{vmatrix}e &f\\h&i \end{vmatrix}
-b \times \begin{vmatrix}d &f\\g&i \end{vmatrix}
+c \times \begin{vmatrix}d &e\\g&h \end{vmatrix}\\
=a(ei-fh)-b(di-fg)+c(dh-eg)
$$

$$
F = \begin{bmatrix}
1 & 4 & 7\\
2 & 5 & 6\\
3 & 4 & 8
\end{bmatrix}\\
\begin{align*}
|F| &= 1 \times ( 5 \times 8 -6 \times 4 )
-4 \times ( 2 \times 8 -6 \times 3 )
+7 \times ( 2 \times 4 -5 \times 3 ) \\
&= 1\times(40-24) -4\times(16-18)+7\times(8-15) \\
&= 1\times(16) -4\times(-2) + 7\times(-7) \\
&=16+8-49 \\
&= 24 - 49 \\
&=-25
\end{align*}
$$

In [ ]:
F = np.array([[1,4,7],
              [2,5,6],
              [3,4,8]])
np.linalg.det(F)

-25.000000000000007

# Inverse Matrix

In [ ]:
F = np.array([[1,4,7],
              [2,5,6],
              [3,4,8]])
np.linalg.inv(F)

array([[-0.64,  0.16,  0.44],
       [-0.08,  0.52, -0.32],
       [ 0.28, -0.32,  0.12]])